language: php
script: phpunit tests

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.18

matrix:
  include:
    - php: hhvm
      dist: trusty


before_script:
    - composer install
    - phpunit --version
