language: php
script: phpunit tests

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: hhvm-3.6
      dist: trusty
    - php: hhvm-3.9
      dist: trusty
    - php: hhvm-3.12
      dist: trusty
    - php: hhvm-3.15
      dist: trusty
    - php: hhvm-3.18
      dist: trusty


before_script:
    - composer install
    - phpunit --version
