<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */


spl_autoload_register(function ($class) {
    /*
        This array has a map of (class => file)
    */

    // classes {{{
    static $classes = array (
  'notoj\\notoj' => '/Notoj.php',
  'notoj\\annotation' => '/Annotation.php',
  'notoj\\file' => '/File.php',
  'notoj\\annotations' => '/Annotations.php',
  'notoj\\annotationbase' => '/AnnotationBase.php',
  'notoj\\tokenizer' => '/Tokenizer.php',
  'notoj\\dir' => '/Dir.php',
  'notoj_yytoken' => '/Parser.php',
  'notoj_yystackentry' => '/Parser.php',
  'notoj_parser' => '/Parser.php',
  'notoj\\reflectionfunction' => '/ReflectionFunction.php',
  'notoj\\reflectionproperty' => '/ReflectionProperty.php',
  'notoj\\reflectionmethod' => '/ReflectionMethod.php',
  'notoj\\reflectionclass' => '/ReflectionClass.php',
  'notoj\\reflectionobject' => '/ReflectionObject.php',
);
    // }}}

    // deps {{{
    static $deps    = array (
  'notoj\\notoj' => 
  array (
    0 => 'notoj\\annotationbase',
    1 => 'notoj\\annotation',
  ),
  'notoj\\annotation' => 
  array (
    0 => 'notoj\\annotationbase',
  ),
  'notoj\\file' => 
  array (
    0 => 'notoj\\annotationbase',
    2 => 'notoj\\annotation',
    3 => 'notoj\\annotations',
    6 => 'notoj\\notoj',
  ),
  'notoj\\annotations' => 
  array (
    0 => 'notoj\\annotationbase',
    2 => 'notoj\\annotation',
  ),
  'notoj\\tokenizer' => 
  array (
    0 => 'notoj\\annotationbase',
    1 => 'notoj\\annotation',
    2 => 'notoj\\notoj',
  ),
  'notoj\\dir' => 
  array (
    0 => 'notoj\\annotationbase',
    2 => 'notoj\\annotation',
    3 => 'notoj\\annotations',
    6 => 'notoj\\notoj',
    7 => 'notoj\\file',
  ),
  'notoj\\reflectionfunction' => 
  array (
    0 => 'notoj\\annotationbase',
    1 => 'notoj\\annotation',
    2 => 'notoj\\notoj',
  ),
  'notoj\\reflectionproperty' => 
  array (
    0 => 'notoj\\annotationbase',
    1 => 'notoj\\annotation',
    2 => 'notoj\\notoj',
  ),
  'notoj\\reflectionmethod' => 
  array (
    0 => 'notoj\\annotationbase',
    1 => 'notoj\\annotation',
    2 => 'notoj\\notoj',
  ),
  'notoj\\reflectionclass' => 
  array (
    0 => 'notoj\\annotationbase',
    1 => 'notoj\\annotation',
    2 => 'notoj\\notoj',
  ),
  'notoj\\reflectionobject' => 
  array (
    0 => 'notoj\\annotationbase',
    1 => 'notoj\\annotation',
    2 => 'notoj\\notoj',
  ),
);
    // }}}

    $class = strtolower($class);
    if (isset($classes[$class])) {
        if (!empty($deps[$class])) {
            foreach ($deps[$class] as $zclass) {
                if (!class_exists($zclass, false)) {
                    require __DIR__  . $classes[$zclass];
                }
            }
        }

        if (!class_exists($class, false)) {
            require __DIR__  . $classes[$class];
        }
        return true;
    }

    return false;
});


